'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Profile={id:string;email:string;full_name:string|null;nickname:string|null;role:'admin'|'manager'|'teammate'|'dev';requested_role:'manager'|'teammate'|'dev';status:'pending'|'active'|'inactive'|'terminated';timezone:string;onboarding_complete:boolean}
type TimeEntry={id:string;work_date:string;clock_in:string;clock_out:string|null;ot_eligible:boolean;is_unscheduled:boolean}
const supabase=createClient()

export default function Home(){
 const [userId,setUserId]=useState<string|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('Dashboard'),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function refreshProfile(uid?:string){const id=uid||userId;if(!id)return;const{data,error}=await supabase.from('profiles').select('*').eq('id',id).single();if(error)setError(error.message);else setProfile(data as Profile)}
 useEffect(()=>{let mounted=true;supabase.auth.getUser().then(async({data})=>{if(!mounted)return;const uid=data.user?.id||null;setUserId(uid);if(uid)await refreshProfile(uid);setLoading(false)});const{data:listener}=supabase.auth.onAuthStateChange(async(_e,s)=>{const uid=s?.user?.id||null;setUserId(uid);if(uid)await refreshProfile(uid);else setProfile(null)});return()=>{mounted=false;listener.subscription.unsubscribe()}},[])
 if(loading)return <Center><div className="card">Loading portal…</div></Center>
 if(!userId)return <AuthScreen/>
 if(!profile?.onboarding_complete)return <Onboarding onDone={()=>refreshProfile()}/>
 if(profile.status==='pending')return <Center><div className="card auth-card"><h1>Pending approval</h1><p className="muted">Your profile was submitted. An Admin or Manager must approve it before access is enabled.</p><div className="row"><span>Requested role</span><strong>{profile.requested_role}</strong></div><button className="btn btn-secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></Center>
 if(profile.status!=='active')return <Center><div className="card auth-card"><h1>Account unavailable</h1><p>Your account status is <strong>{profile.status}</strong>.</p><button className="btn btn-secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></Center>
 const management=profile.role==='admin'||profile.role==='manager';const tabs=['Dashboard','Time Tracking','Leave','Schedule',...(management?['Manager']:[])]
 return <div className="shell"><aside className="sidebar"><div className="brand">Hypertide</div><div className="nav">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div></aside><main className="main"><div className="topbar"><div><h1 style={{margin:0}}>{tab}</h1><div className="muted">Welcome, {profile.nickname||profile.full_name||profile.email}</div></div><div className="actions"><span className="pill">{profile.role}</span><button className="btn btn-secondary" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></div>{message&&<div className="success" style={{marginBottom:16}}>{message}</div>}{error&&<div className="error" style={{marginBottom:16}}>{error}</div>}{tab==='Dashboard'&&<Dashboard profile={profile}/>} {tab==='Time Tracking'&&<TimeTracking setMessage={setMessage} setError={setError}/>} {tab==='Leave'&&<Leave setMessage={setMessage} setError={setError}/>} {tab==='Schedule'&&<Schedule/>} {tab==='Manager'&&management&&<Manager/>}</main></div>
}

function Center({children}:{children:React.ReactNode}){return <div className="auth-wrap">{children}</div>}

function AuthScreen(){const[mode,setMode]=useState<'login'|'signup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');if(mode==='signup'){const{error}=await supabase.auth.signUp({email,password});if(error)setError(error.message);else setNotice('Account created. Check your email if confirmation is enabled, then sign in.')}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}setBusy(false)}return <Center><div className="card auth-card"><h1 className="title">Hypertide Team Portal</h1><p className="subtitle">Scheduling, attendance, leave, and approvals.</p><form className="stack" onSubmit={submit}><label className="field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}<button className="btn btn-primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="btn btn-secondary" style={{marginTop:12,width:'100%'}} onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Create a new account':'Already have an account? Sign in'}</button></div></Center>}

function Onboarding({onDone}:{onDone:()=>void}){const[fullName,setFullName]=useState(''),[nickname,setNickname]=useState(''),[timezone,setTimezone]=useState('Asia/Manila'),[role,setRole]=useState('teammate'),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const{error}=await supabase.rpc('complete_my_profile',{p_full_name:fullName,p_nickname:nickname,p_timezone:timezone,p_requested_role:role});if(error)setError(error.message);else onDone();setBusy(false)}return <Center><div className="card" style={{width:'min(680px,100%)'}}><h1 className="title">Set up your profile</h1><p className="subtitle">Complete your details. Your account stays pending until approved.</p><form className="stack" onSubmit={submit}><div className="form-grid"><label className="field"><span>Full name</span><input value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label className="field"><span>Nickname</span><input value={nickname} onChange={e=>setNickname(e.target.value)}/></label><label className="field"><span>Requested role</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="teammate">Teammate</option><option value="dev">Dev</option><option value="manager">Manager</option></select></label><label className="field"><span>Timezone</span><select value={timezone} onChange={e=>setTimezone(e.target.value)}><option>Asia/Manila</option><option>Asia/Kolkata</option><option>America/Los_Angeles</option><option>America/New_York</option><option>Europe/London</option><option>Europe/Berlin</option></select></label></div>{error&&<div className="error">{error}</div>}<button className="btn btn-primary" disabled={busy}>{busy?'Saving…':'Submit profile'}</button></form></div></Center>}

function Dashboard({profile}:{profile:Profile}){return <div className="grid"><div className="card"><div className="muted">Status</div><div className="metric">Active</div></div><div className="card"><div className="muted">Timezone</div><div className="metric" style={{fontSize:22}}>{profile.timezone}</div></div><div className="card"><div className="muted">Role</div><div className="metric" style={{textTransform:'capitalize'}}>{profile.role}</div></div></div>}

function TimeTracking({setMessage,setError}:{setMessage:(s:string)=>void;setError:(s:string)=>void}){const[entry,setEntry]=useState<TimeEntry|null>(null),[onBreak,setOnBreak]=useState(false),[recent,setRecent]=useState<TimeEntry[]>([]);async function load(){const{data}=await supabase.from('time_entries').select('*').order('clock_in',{ascending:false}).limit(7);const rows=(data||[]) as TimeEntry[];setRecent(rows);setEntry(rows.find(x=>!x.clock_out)||null);const{data:breaks}=await supabase.from('breaks').select('id').is('ended_at',null).limit(1);setOnBreak(Boolean(breaks?.length))}useEffect(()=>{load()},[]);async function run(fn:string,ok:string){setError('');setMessage('');const{error}=await supabase.rpc(fn);if(error)setError(error.message);else{setMessage(ok);await load()}}return <div className="stack"><div className="card"><h2>Current shift</h2><p className="muted">Server time is used for attendance.</p><div className="actions">{!entry&&<button className="btn btn-primary" onClick={()=>run('clock_in_now','Clocked in successfully.')}>Clock In</button>}{entry&&!onBreak&&<button className="btn btn-secondary" onClick={()=>run('start_paid_break','Paid break started.')}>Start Break</button>}{entry&&onBreak&&<button className="btn btn-secondary" onClick={()=>run('end_paid_break','Break ended.')}>Resume Work</button>}{entry&&<button className="btn btn-primary" onClick={()=>run('clock_out_now','Clocked out successfully.')}>Clock Out</button>}</div>{entry&&<p className="muted">Clocked in: {new Date(entry.clock_in).toLocaleString()}</p>}</div><div className="card"><h2>Recent entries</h2><div className="list">{recent.map(r=><div className="row" key={r.id}><div><strong>{r.work_date}</strong><div className="muted">{new Date(r.clock_in).toLocaleTimeString()} → {r.clock_out?new Date(r.clock_out).toLocaleTimeString():'Open'}</div></div><span className="pill">{r.ot_eligible?'OT eligible':r.is_unscheduled?'Unscheduled':'Regular'}</span></div>)}</div></div></div>}

function Leave({setMessage,setError}:{setMessage:(s:string)=>void;setError:(s:string)=>void}){const[type,setType]=useState('vacation'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[dayType,setDayType]=useState('full'),[reason,setReason]=useState(''),[history,setHistory]=useState<any[]>([]);async function load(){const{data}=await supabase.from('leave_requests').select('*').order('created_at',{ascending:false});setHistory(data||[])}useEffect(()=>{load()},[]);async function submit(e:FormEvent){e.preventDefault();setMessage('');setError('');const days=Math.max(1,Math.round((new Date(end).getTime()-new Date(start).getTime())/86400000)+1),credits=dayType==='half'?0.5:days;const{data:auth}=await supabase.auth.getUser();const{error}=await supabase.from('leave_requests').insert({employee_id:auth.user?.id,leave_type:type,start_date:start,end_date:end,day_type:dayType,credits_requested:credits,reason,status:'pending'});if(error)setError(error.message);else{setMessage('Leave request submitted.');setStart('');setEnd('');setReason('');await load()}}return <div className="stack"><div className="card"><h2>File leave</h2><form className="stack" onSubmit={submit}><div className="form-grid"><label className="field"><span>Leave type</span><select value={type} onChange={e=>setType(e.target.value)}><option value="vacation">Vacation</option><option value="sick">Sick</option></select></label><label className="field"><span>Day type</span><select value={dayType} onChange={e=>setDayType(e.target.value)}><option value="full">Full day</option><option value="half">Half day</option></select></label><label className="field"><span>Start date</span><input type="date" value={start} onChange={e=>setStart(e.target.value)} required/></label><label className="field"><span>End date</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></label></div><label className="field"><span>Reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3}/></label><button className="btn btn-primary">Submit leave request</button></form></div><div className="card"><h2>Leave history</h2><div className="list">{history.map(h=><div className="row" key={h.id}><div><strong>{h.leave_type}</strong><div className="muted">{h.start_date} to {h.end_date} · {h.credits_requested} credit(s)</div></div><span className="pill">{h.status}</span></div>)}</div></div></div>}

function Schedule(){return <div className="card"><h2>Schedule</h2><p className="muted">Recurring schedules, Pacific Time conversion, weekend rotation, shift swaps, and date-specific overrides are connected to the database. The editable weekly schedule form is the next UI module.</p><div className="row"><span>Management timezone</span><strong>America/Los_Angeles</strong></div></div>}

function Manager(){const[pending,setPending]=useState<Profile[]>([]),[all,setAll]=useState<Profile[]>([]);async function load(){const{data}=await supabase.from('profiles').select('*').order('created_at',{ascending:false});const rows=(data||[]) as Profile[];setAll(rows);setPending(rows.filter(p=>p.status==='pending'&&p.onboarding_complete))}useEffect(()=>{load()},[]);async function approve(p:Profile){const{error}=await supabase.rpc('approve_profile',{p_user_id:p.id,p_role:p.requested_role,p_manager_id:null});if(!error)await load();else alert(error.message)}return <div className="stack"><div className="card"><h2>Pending approvals</h2><div className="list">{pending.length===0&&<div className="muted">No pending profiles.</div>}{pending.map(p=><div className="row" key={p.id}><div><strong>{p.full_name||p.email}</strong><div className="muted">{p.email} · requests {p.requested_role}</div></div><button className="btn btn-primary" onClick={()=>approve(p)}>Approve</button></div>)}</div></div><div className="card"><h2>People</h2><div className="list">{all.map(p=><div className="row" key={p.id}><div><strong>{p.full_name||p.email}</strong><div className="muted">{p.email} · {p.timezone}</div></div><span className="pill">{p.role} / {p.status}</span></div>)}</div></div></div>}
